print("School Resources Project")
print("")
location = (input("Enter the location: "))
print("")
print("Data Collection: ")
print("")
print("1. Water fountains: ")
total_fountains = (int(input("  - Enter the amount of water fountains: ")))
fountain_locations = (input("  - Enter the locations of the fountains (seperated by commas): "))
fountain_condition = (input("  - Enter the condition of the fountains: "))
print("")
print("2. Restrooms: ")
total_restrooms = (int(input("  - Enter the number of restrooms: ")))
restroom_locations = (input("  - Enter the locations of the restrooms (Seperated by commas): "))
restroom_condition = (input("  - Enter the cleanliness of the restrooms: "))
print("")
print("3. Staff offices: ")
total_offices = (int(input("  - Enter the number of staff offices: ")))
office_locations = (input("  - Enter the locations of the offices (Seperated by commas): "))
print("")
print("4. Classrooms: ")
total_classrooms = (int(input("  - Enter the number of classrooms: ")))
classroomFountain_density = (float(total_fountains/total_classrooms))
classroomRestroom_density = (float(total_restrooms/total_classrooms))
officeRestroom_density = (float(total_restrooms/total_offices))
y = "{:.2f}".format(classroomFountain_density)
x = "{:.2f}".format(classroomRestroom_density)
z = "{:.2f}".format(officeRestroom_density)
print("")
print("")
print("")
print("**Data Collected:**")
print("")
print("1. Water Fountains: ")
print(F"  - Number of water founains: {total_fountains}")
print(f"  - Locations: {fountain_locations}")
print(f"  - Condition: {fountain_condition}")
print("")
print("2. Restrooms: ")
print(f"  - Number of Restrooms: {total_restrooms}")
print(f"  - Locations: {restroom_locations}")
print(f"  - Cleanliness: {restroom_condition}")
print("")
print("3.  Staff Offices: ")
print(f"  - Number of offices: {total_offices}")
print(f"  - Locations: {office_locations}")
print(f"  - Number of restrooms per office: {z}")
print("")
print("4. Classrooms")
print(f"  - Total number of classrooms: {total_classrooms}")
print(f"  - Number of water fountains per classroom: {y}")
print(f"  - Number of restrooms per classroom: {x}")